### ISSUE TITLE
socialwiki doesn't back up in moodle backup

### ISSUE THREAD

**Issue by ntartania** [NMAI-lab/moodle-mod_socialwiki#64] opened 2016-01-26 18:07 UTC
Moodle allows activities or entire courses to be backed up to arcive files.
I attempted to backup a socialwiki activity on its own, or an entire course containing a socialwiki, and the socialwiki pages don't appear in the backup.
there's a socialwiki directory with some stuff, but not the pages.

**Comment by bencroskery** [comment] 2016-01-27 19:36
The pages are actually held in the main socialwiki.xml file along with the subwikis (almost always only 1). I looked through a backup and all the pages seem to be there meaning there must be an issue with the restore process.

I will take a look at revamping the the backup/restore files and might end up splitting the pages, subwikis and main wiki file apart to match the database.

**Comment by ntartania** [comment] 2016-01-27 19:53
Check the sysc3020 course. There are 3 backup files stored there, and the first two (jan 26th) are tiny -- I don't know what I did wrong but they clearly don't have the pages there.
I tried again and this time the file is bigger but the socialwiki.xml doesn't seem to contain the page content. It has other fields but the content is empty. I didn't check by restoring it, I checked by opening the backup file with a zip program.

**Comment by bencroskery** [comment] 2016-01-27 19:59
I also noticed the file size fluctuating, although I was working with my own testing server with only a few pages.

I will do some testing with the SYSC3020 backups and see if I can track down where the issue is coming from.

**Comment by bencroskery** [comment] 2016-02-16 20:34
After going through many backups I have narrowed the issue down to content missing if the string length is over ~25 characters. The page content is almost always missing and the title can also be missing if it is long enough.

In the backups I have, this is also a problem with all other activities which have user content (ex. forum activity). Based off this I expect there must be incorrect settings somewhere, otherwise this would be a big issue with the backup system in Moodle.

**Comment by bencroskery** [comment] 2016-02-19 04:33
Issue should be fixed!

There was a PHP warning in a regex replace while running the backups that would block content from passing through. I'm not entirely sure how this error was also affecting all the other backup files, although the problem seems to have disapperared in those places as well.

In a few days I will pull the fixes down to the servers and check that the backups from there will restore properly.

**Closed** 2016-07-09 00:23 UTC
